name: simple_calculator unit test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install f
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest tests/tests_1b.py -v -setup

      - name: generate coverage report
        run: |
          coverage report -m
